# Generated by Django 2.0.5 on 2018-06-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='hours_per_week',
            field=models.IntegerField(default=0),
        ),
    ]
