# Generated by Django 2.0.5 on 2018-05-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_project_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
    ]
