# Generated by Django 2.0.5 on 2018-05-12 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0004_auto_20180508_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('project_owner', models.ForeignKey(on_delete=True, related_name='user_of_description', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=True, related_name='skill_description', to='social.Skill')),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_time',
            new_name='project_timeline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='positions',
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(related_name='user_projects', to='social.Project'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(related_name='user_skills', to='social.Skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='accepted_participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='applicants',
            field=models.ManyToManyField(related_name='applicants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(default='', on_delete=True, related_name='project_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='project_positions', to='social.Skill'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=True, related_name='profile_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
