# Generated by Django 2.0.5 on 2018-05-13 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0006_auto_20180512_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('person_applying', models.ForeignKey(on_delete=True, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='accepted_participants',
        ),
        migrations.RemoveField(
            model_name='project',
            name='applicants',
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=True, related_name='applications', to='social.Project'),
        ),
        migrations.AddField(
            model_name='application',
            name='skill',
            field=models.ForeignKey(on_delete=True, related_name='applications', to='social.Skill'),
        ),
    ]
