# Generated by Django 2.0.5 on 2018-05-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20180516_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='profile',
            name='url_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='url_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
