# Generated by Django 2.0.5 on 2018-05-16 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0011_auto_20180516_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_filled_user',
            field=models.ForeignKey(default='', on_delete=True, related_name='my_position_for_project', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
