# Generated by Django 2.0.5 on 2018-05-17 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_position_position_filled_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='project',
        ),
        migrations.RemoveField(
            model_name='application',
            name='skill',
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.ForeignKey(default='', on_delete=True, related_name='position_applications', to='social.Position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='position_filled_user',
            field=models.ForeignKey(default='', on_delete=True, related_name='my_position_for_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
