# Generated by Django 2.0.5 on 2018-05-17 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20180517_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_filled_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='my_position_for_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
