# Generated by Django 2.0.5 on 2018-05-22 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20180517_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
