# Generated by Django 2.0.5 on 2018-05-31 03:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0019_auto_20180527_0916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('position', 'person_applying')},
        ),
    ]
