# Generated by Django 2.0.5 on 2018-05-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_auto_20180530_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='active',
        ),
    ]
